### ISSUE TITLE
result file is extremely big

### ISSUE THREAD

**Issue by yoavmil** [geometryprocessing/voroffset#2]
I see the result file is a mesh file with lots of dexels. How could I convert this to a mesh I can work with? 
Maybe marching cubes may help, could you advise how to integrate marching cubes? or how to connect the dexels to one large volume?

**Comment by jdumas** [comment]
Hi,

The mesh output is mostly there for visualization purposes. If you want tor reconstruct a 3D mesh out of it, you can dump a point cloud (save output as `.xyz`), and reconstruct a surface using [geogram](http://alice.loria.fr/software/geogram/doc/html/geogram_examples.html), e.g. by running the example program `vorpalite profile=reconstruct my_points.xyz my_surface.obj`
