### ISSUE TITLE
May I ask if it is applicable to Windows?

### ISSUE THREAD

**Issue by Mxp990329** [geometryprocessing/voroffset#4]

**Comment by jdumas** [comment]
Yes, the code should compile on Windows.

**Comment by Mxp990329** [comment]
Thank you for your answer. However, in the Windows system, following the steps you provided to compile, a CMAKE error occurred, and I am currently unsure how to resolve it.
CMake Warning (dev) at cmake/SetWarnings.cmake:133 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy details.  Use the cmake_policy command to set the policy and suppress this warning.
  Quoted variables like "MSVC" will no longer be dereferenced when the policy is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  src/vor2d/CMakeLists.txt:33 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by jdumas** [comment]
Those are only warnings though. Do you have an actual error in your terminal output?

**Comment by Mxp990329** [comment]
> 但这些只是警告。您的终端输出中是否有实际错误？

Thank you for your answer. I am trying to use Mingw to implement 'cmake ..' in Windows. This step was successful. But when I entered the 'make - j8' command, there was an error : Gcc.exe: error:/D_ Secure_ SCL=0: No such file or directory. Still unable to compile successfully . I'm sorry I'm not familiar with CMake .

**Comment by jdumas** [comment]
You should not use MinGW. The project should compile fine using the Visual Studio generator with CMake.

**Comment by Mxp990329** [comment]
> You should not use MinGW. The project should compile fine using the Visual Studio generator with CMake.
Thank you for your answer. When I build using Visual Studio, the prompt after using the 'make -j8' command is: 'make:  * * * No targets specified and no makefile found. Stop.'

**Comment by jdumas** [comment]
The 'make -j8' instructions are for Makefile generators (Linux/macOS). On Windows you can type 'cmake --build . --config Release -j 8' instead.

**Comment by jdumas** [comment]
I have updated the compilation instructions in the README. Closing this.
