### ISSUE TITLE
Confusion about the parameter '--radius'

### ISSUE THREAD

**Issue by Alan-Leo-Wong** [geometryprocessing/voroffset#5]
I want to dilate the input mesh by a distance $\delta$(e.g. $10$), then I run the program:
`./offset3d -i bunny.obj -o bunny_res.xyz -d 1 -r 10 -x dilation`
However, the result is wrong, which means the generated points don't lie on the position with a distance of $10$ from mesh. And, it seems that the point cloud has been truncated, as shown in the figure.
![image](https://github.com/geometryprocessing/voroffset/assets/47875865/91c52bf8-e7b6-49ad-a3d8-029629578a6b)
So, how do I adjust my parameters? Thanks a lot.

**Comment by jdumas** [comment]
Hi. The `--radius` argument is expressed in number of dexels. If you want to specify a distance you need to use `--radius_in_mm` instead. As for the truncated points on the border, you need to add a sufficient `--padding` to represent the dilated result (again `--padding` is expressed in number of dexels here).

**Comment by Alan-Leo-Wong** [comment]
I get it, thx!
