### ISSUE TITLE
Request for baseline code

### ISSUE THREAD

**Issue by awxdnb** [geometryprocessing/voroffset#6]
Hi,
In your paper, you compared with "Polygonal boundary evaluation of Minkowski sums and swept volumes." However, it seems that the code for this method is not open source. Could you please consider providing the code for this method? Your assistance is greatly appreciated.

**Comment by jdumas** [comment]
Hi. I would suggest that you contact the authors directly and ask them for an executable or ask them to run a comparison for you.

**Comment by awxdnb** [comment]
Ok! Thanks for your suggestion!
