### ISSUE TITLE
Mac ARM build error

### ISSUE THREAD

**Issue by lslzl3000** [geometryprocessing/voroffset#7]
the `cmake ..` works fine on mac m2 arm based system, but during `cmake --build . -j8 --config Release` there are some errors about `__builtin_ia32_xxxxx`, e.g:

![Screenshot 2024-03-26 at 15 36 42](https://github.com/geometryprocessing/voroffset/assets/3398981/3c9fb7c1-9ed2-4467-9a4f-a6431ef0222a)

any way to solve these problem?

**Comment by jdumas** [comment]
Thanks for the report. Which .cpp does the error come from exactly? My guess would be geogram. This code was written against an old version of geogram when macOS arm64 didn't exist yet. Fixing this would require updating the geogram dependency. Feel free to submit a PR for that, as I'm not sure if/when I'll have to fix it myself. In the meantime I suggest compiling with rosetta in x86 mode.

**Comment by lslzl3000** [comment]
Thanks for the tips, I can make it in x86 mode
