### ISSUE TITLE
How to build a standalone offset3d

### ISSUE THREAD

**Issue by lslzl3000** [geometryprocessing/voroffset#8]
I tried build within github action macos runner, it works fine, but it seems always use the shared libs after build. The final binary `offset3d` was only 5xx kb and always contains the `lib` folder. 

I tried add the `set(BUILD_SHARED_LIBRARIES ON)` or `set(BUILD_SHARED_LIBRARIES OFF)`, but the result is the same, nothing different.  
Is there a way to build a standalone binary `offset3d`?

By the way, event with the shared `lib` folder, the `offset3d` seems build with a absolute path for the `lib`. After copy `offset3d` and `lib` to anther macs, the `offset3d` still use the absolute path from github runner.

![Screenshot 2024-03-26 at 23 53 48](https://github.com/geometryprocessing/voroffset/assets/3398981/613e326d-9de5-4c78-8faf-5a0b83679b95)

Can it run with a relative `lib` path?

**Comment by jdumas** [comment]
The CMake flag to control whether to build shared libraries or not is `BUILD_SHARED_LIBS`. For the Geogram dependency, you may need to additionally set the [VORPALINE_BUILD_DYNAMIC](https://github.com/alicevision/geogram/blob/05aca7aa0a1eb83c912cd7126bdd1da352dc1e66/cmake/geogram.cmake#L77) option. On my macOS everything builds as a static lib by default apart from Geogram (which requires the flag above to be set to OFF).

Regarding absolute paths in the final program, we're not doing anything specific regarding @rpath handling on macOS. Creating relocatable executable is kinda complicated and this codebase doesn't support that. Feel free to modify the CMake and create install rules & handle rpath issues. But this is research code so I can't provide support for that.
